#Dev environment
version: '2'

services:
    listener:
        image: handsoff/listen
        ports:
          - "5000:5000/udp"
          - "5001:5001"
        links:
          - message_queue

    message_queue:
        image: handsoff/message-queue
        ports:
          - "5672:5672"
          - "15672:15672"
        volumes:
          - /opt/data:/var/lib/rabbitmq

    parser:
        image: handsoff/parser
        ports:
          - "7001:7001"
